
import Image from "next/image";
import DisplayCard from "../DisplayCard";
import BookingModal from "@/component/BookingModal";
import DeleteBooking from "@/component/BookingDelete";
import UpdateBooking from "@/component/UpdateBooking";

import { headers } from "next/headers";
import { auth } from "@/lib/auth";
export const metadata = {
  title: "StudyNook || Room Details",
  description: "Generated by create next app",
};
const DetailsRoom = async ({ params }) => {
  const session = await auth.api.getSession({
    headers: await headers()
  })

  const userId = session?.user.id
  const user = session?.user
  const userName = session?.user?.name
  const { id } = await params
  const res = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URI}/studyrooms/${id}`)
  const room = await res.json()
  const { floor, total, capacity_max, roomCreator } = room;

  const filterName = roomCreator == userName

  const userBookingReq = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URI}/usersrooms/${userId}`)
  const userBookingData = await userBookingReq.json()

  return (
    <div className="max-w-300 mx-auto pt-10 sm:px-10">

      <div className="grid md:grid-cols-4 grid-cols-1 gap-5">
        <div className="col-span-2">

          <DisplayCard room={room} />

        </div>
        <div className="col-span-2">
          <div className="border border-gray-200 dark:border-gray-700 
    bg-gray-50 dark:bg-gray-900 
    shadow-lg rounded-xl p-6 
    transition-all duration-300 
    hover:shadow-2xl hover:-translate-y-1">

            {/* price top */}
            <div className="flex justify-between items-center mb-10">
              <h2 className="text-3xl font-bold text-rose-500 dark:text-rose-400">
                $ {total || 0}
              </h2>

              <span className="text-emerald-600 dark:text-emerald-400 
        font-bold bg-emerald-100 dark:bg-emerald-900/40 
        px-3 py-1 rounded-full">
                Total Cost
              </span>
            </div>

            {/* floor + booking */}
            <div className="mt-3 space-y-2 flex flex-col text-sm text-gray-700 dark:text-gray-300">

              <span className="hover:bg-blue-100 dark:hover:bg-blue-900/30 px-2 py-1 rounded-md transition">
                <span className="text-emerald-600 dark:text-emerald-400 font-semibold">
                  {floor}
                </span> Floor
              </span>

              <span className="hover:bg-rose-100 dark:hover:bg-rose-900/30 px-2 py-1 rounded-md transition">
                <span className="text-rose-500 dark:text-rose-400 font-semibold">{userBookingData?.length} </span>
                Total Booking
              </span>

              <span className="hover:bg-amber-100 dark:hover:bg-amber-900/30 px-2 py-1 rounded-md transition">
                <span className="text-amber-600 dark:text-amber-400 font-semibold">
                  {capacity_max}
                </span> Up to people
              </span>

            </div>

            {/* booking */}
            <div className="mt-4 hover:scale-[1.02] transition-transform duration-300">
              <BookingModal room={room} />
            </div>

            {/* owner actions */}
            {filterName && (
              <div className="flex gap-3 mt-5 justify-center">

                <div className="btn w-[48%] 
           hover:bg-blue-600 
           dark:hover:bg-blue-500 
          text-white border-none 
          transition-all duration-300 hover:scale-105">
                  <UpdateBooking room={room} />
                </div>

                <div className="btn w-[48%]   text-white border-none 
          transition-all duration-300 hover:scale-105">
                  <DeleteBooking room={room} />
                </div>

              </div>
            )}
          </div>

          {/* Listed by */}
          <div className="mt-5 p-5 border border-gray-200 dark:border-gray-700 
      rounded-xl shadow-xl    
      bg-gradient-to-r from-gray-50 to-gray-100 
      dark:from-gray-900 dark:to-gray-800 
      hover:shadow-2xl transition-all duration-300 hover:scale-[1.02]">
            <h1 className="text-xl font-semibold mb-2 text-gray-700 dark:text-gray-200">
              Listed by
            </h1>
            <div className="flex gap-5 p-5 items-center">


              <div>
                <Image
                  width={50}
                  height={50}
                  alt={user?.name}
                  src={user?.image}
                  className="h-20 w-20 rounded-full object-cover 
          border-2 border-gray-300 dark:border-gray-600"
                />
              </div>

              <div>
                <h1 className="font-bold text-gray-800 dark:text-gray-100">
                  {user?.name}
                </h1>
                <p className="text-gray-500 dark:text-gray-400">
                  {user?.email}
                </p>
              </div>

            </div>
          </div>
        </div>

      </div>
    </div>
  );
};

export default DetailsRoom;