import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="">
        
        <Navbar/>
        <main className="">
          {children}
        </main>

        </body>
    </html>
  );
}
