import { setServers } from "node:dns";
setServers(["8.8.8.8", "8.8.4.4"]);

import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { Toaster } from "react-hot-toast";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata = {
  title: "StudyNook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="dark:border-gray-700 
    bg-gray-50 dark:bg-gray-900/50">

        <Navbar />
        <main className=" ">
          {children}
        </main>
        <Footer />
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
