import LoginPage from "./LoginPage";
export const metadata = {
  title: "StudyRoom || Login",
  description: "Generated by create next app",
};
const login = () => {
  return (
    <LoginPage />
  )
}
export default login;