
import MyBookingListDeletePage from "@/component/MyBookingListDelete";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import Image from "next/image";
import Link from "next/link";
import { MdEventBusy } from "react-icons/md";
export const metadata = {
  title: "StudyNook || My Bookings",
  description: "Generated by create next app",
};
const MyBookingPage = async () => {
  const session = await auth.api.getSession({
    headers: await headers()
  })
  const userId = session?.user.id
  const { token } = await auth.api.getToken({
    headers: await headers()
  })

  const userBookingReq = await fetch(`${process.env.NEXT_PUBLIC_SERVER_URI}/usersrooms/${userId}`, {
    headers: {
      authorization: `Bearer ${token}`
    }
  })
  const userBookingData = await userBookingReq.json()

  return (
    <div className="max-w-300 mx-auto">

      {/* HEADER */}
      <div className="pt-10 mb-8 space-y-4">
        <h1 className="text-3xl font-bold text-base-content">
          My Bookings
        </h1>
        <p className="text-base-content/60 text-lg">
          Manage your upcoming and past room reservations easily
        </p>
      </div>

      {/* EMPTY STATE */}
      {userBookingData?.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 px-6 text-center rounded-2xl border border-base-300 bg-base-100 shadow">

          <MdEventBusy className="text-6xl text-indigo-500 mb-4" />

          <h2 className="text-2xl font-bold text-base-content">
            No Bookings Found
          </h2>

          <p className="text-base-content/60 mt-3 max-w-md">
            You haven’t booked any study rooms yet. Start exploring available rooms
            and make your first reservation.
          </p>

          <Link href="/">
            <button className="mt-6 btn bg-indigo-500 hover:bg-indigo-600 text-white border-none">
              Back Home
            </button>
          </Link>

        </div>
      ) : (
        /* TABLE */
        <div className="overflow-x-auto rounded-2xl border border-base-300">
          <table className="table w-full bg-base-100 min-w-[900px]">

            <thead className="bg-base-200">
              <tr>
                <th>Room</th>
                <th>Date</th>
                <th>Time</th>
                <th>Total Cost</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>
              {userBookingData?.map((room) => (
                <tr key={room._id} className="border-t border-base-300 hover:bg-base-200/40 transition">

                  <td className="px-4 py-4">
                    <div className="flex items-center gap-3">
                      <Image
                        width={60}
                        height={60}
                        src={room.image}
                        alt={room.name}
                        className="rounded-xl object-cover"
                      />
                      <div>
                        <h2 className="font-semibold">{room.name}</h2>
                        <p className="text-xs text-base-content/60">
                          Floor {room.floor}
                        </p>
                      </div>
                    </div>
                  </td>

                  <td className="px-4 py-4">{room.date}</td>

                  <td className="px-4 py-4">
                    {room.startTime} - {room.endTime}
                  </td>

                  <td className="px-4 py-4 font-bold text-primary">
                    ${room.total}
                  </td>

                  <td className="px-4 py-4">
                    <span className={`px-3 py-1 rounded-full text-sm font-semibold
                  ${room.status === "Confirmed"
                        ? "bg-emerald-500/15 text-emerald-500"
                        : "bg-rose-500/15 text-rose-500"
                      }`}>
                      {room.status}
                    </span>
                  </td>

                  <td className="px-4 py-4">
                    {room.status === "Confirmed" ?
                      <button className="btn text-white">
                        <MyBookingListDeletePage room={room} />
                      </button>
                      :
                      <span className="text-4xl">-</span>
                    }
                  </td>

                </tr>
              ))}
            </tbody>

          </table>
        </div>
      )}
    </div>
  );
};

export default MyBookingPage;